name: CI

on:
   push: 
      branches: [ master ]
   pull_request:
      branches: [ master ]
   workflow_dispatch:

jobs: 
   builds:
    
     runs-on: ubuntu-latest
    
  steps:
  
   - uses: action/checkout@v2
   
   - name: Run a one-line script
     run: echo Hello< Multiplatform!

   -name: Run a mutli-line script
    run: |
      echo add other actions to build,
      echo test and deploy the project.
